### ISSUE TITLE
Remove "Learn more" button from event sections

### ISSUE THREAD

**Issue by GBergatto** [Team-Isaac-Polito/isaac-website#225]
Remove the "Learn more" button from the section about a specific event in the Events page as we don't plan to have a dedicated page for each event.

![image](https://github.com/Team-Isaac-Polito/isaac-website/assets/69045457/6ebd184c-ec49-4a20-871d-240a365d2be2)

**Comment by cristinagenduso** [comment]
The "Learn More" button was intended to link to external pages for each event, such as the Polito page referencing Salone dell'Orientamento or the page about the Maker Faire, to enhance our credibility. For now, I will remove it.

**Comment by GBergatto** [comment]
Ah nice, I didn't think of that
